### ISSUE TITLE
can not show indictator when pull

### ISSUE THREAD

**Issue by abbothzhang** [jsdf/react-native-refreshable-listview#28] opened 2015-11-15 12:10 UTC
can not show indictator when pull

**Comment by abbothzhang** [comment] 2015-11-15 12:29
Spinner Doesn't Show Up #12

**Comment by jsdf** [comment] 2015-11-28 00:53
can you give me an example of how you are using the component, including which props you are passing in

**Comment by jsdf** [comment] 2015-11-30 23:27
Closing due to insufficient information provided to reproduce the issue.

**Closed by jsdf** 2015-11-30 23:27 UTC
